#!/bin/bash

# LifeMetrics .env Setup Script
# This script helps you create a .env file with secure generated keys

set -e

echo "🚀 LifeMetrics Environment Setup"
echo "================================="
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled."
        exit 1
    fi
    echo ""
fi

# Check if Python is available
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is not installed. Please install Python 3 first."
    exit 1
fi

echo "📝 Generating secure keys..."
echo ""

# Generate secure keys
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
JWT_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")

# Generate passwords
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")
REDIS_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")
MINIO_ROOT_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")

echo "✅ Security keys generated"
echo "✅ Passwords generated"
echo ""

# Ask for OAuth credentials
echo "🔗 OAuth2 Setup (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You can skip OAuth setup now and add it later."
echo "Press Enter to skip, or enter your credentials."
echo ""

# GitHub
echo "GitHub OAuth:"
read -p "  GitHub Client ID (or press Enter to skip): " GITHUB_CLIENT_ID
if [ -n "$GITHUB_CLIENT_ID" ]; then
    read -p "  GitHub Client Secret: " GITHUB_CLIENT_SECRET
else
    GITHUB_CLIENT_ID="your-github-client-id"
    GITHUB_CLIENT_SECRET="your-github-client-secret"
fi
echo ""

# Google
echo "Google OAuth (Gmail, Calendar):"
read -p "  Google Client ID (or press Enter to skip): " GOOGLE_CLIENT_ID
if [ -n "$GOOGLE_CLIENT_ID" ]; then
    read -p "  Google Client Secret: " GOOGLE_CLIENT_SECRET
else
    GOOGLE_CLIENT_ID="your-google-client-id"
    GOOGLE_CLIENT_SECRET="your-google-client-secret"
fi
echo ""

# Twitter
echo "Twitter OAuth:"
read -p "  Twitter Client ID (or press Enter to skip): " TWITTER_CLIENT_ID
if [ -n "$TWITTER_CLIENT_ID" ]; then
    read -p "  Twitter Client Secret: " TWITTER_CLIENT_SECRET
else
    TWITTER_CLIENT_ID="your-twitter-client-id"
    TWITTER_CLIENT_SECRET="your-twitter-client-secret"
fi
echo ""

# Create .env file
echo "📄 Creating .env file..."

cat > .env << EOF
# LifeMetrics Environment Configuration
# Generated by setup-env.sh on $(date)
# NEVER commit this file to version control

# Application
APP_NAME=LifeMetrics
APP_ENV=development
DEBUG=true
SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Backend
BACKEND_HOST=0.0.0.0
BACKEND_PORT=8000
BACKEND_RELOAD=true

# Frontend
FRONTEND_HOST=0.0.0.0
FRONTEND_PORT=3000

# Database
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=lifemetrics
POSTGRES_USER=lifemetrics_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+asyncpg://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@\${POSTGRES_HOST}:\${POSTGRES_PORT}/\${POSTGRES_DB}

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_DB=0
REDIS_URL=redis://:\${REDIS_PASSWORD}@\${REDIS_HOST}:\${REDIS_PORT}/\${REDIS_DB}

# MinIO (S3-compatible storage)
MINIO_HOST=minio
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET=lifemetrics-data

# Ollama (Local LLM)
OLLAMA_HOST=ollama
OLLAMA_PORT=11434
OLLAMA_BASE_URL=http://\${OLLAMA_HOST}:\${OLLAMA_PORT}
OLLAMA_MODEL=llama3.2
OLLAMA_TIMEOUT=120

# Celery
CELERY_BROKER_URL=\${REDIS_URL}
CELERY_RESULT_BACKEND=\${REDIS_URL}
CELERY_WORKER_CONCURRENCY=4

# OAuth2 - GitHub
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
GITHUB_REDIRECT_URI=http://localhost:8000/api/oauth/github/callback

# OAuth2 - Twitter/X
TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
TWITTER_REDIRECT_URI=http://localhost:8000/api/oauth/twitter/callback

# OAuth2 - Google (Gmail, Calendar)
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=http://localhost:8000/api/oauth/google/callback

# OAuth2 - Slack (not implemented yet)
SLACK_CLIENT_ID=your-slack-client-id
SLACK_CLIENT_SECRET=your-slack-client-secret
SLACK_REDIRECT_URI=http://localhost:8000/api/oauth/slack/callback

# OAuth2 - Spotify (not implemented yet)
SPOTIFY_CLIENT_ID=your-spotify-client-id
SPOTIFY_CLIENT_SECRET=your-spotify-client-secret
SPOTIFY_REDIRECT_URI=http://localhost:8000/api/oauth/spotify/callback

# Data Collection
COLLECTION_INTERVAL_MINUTES=60
DATA_RETENTION_DAYS=365
ENABLE_AUTO_COLLECTION=true

# Security
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_ALGORITHM=HS256
JWT_EXPIRATION_MINUTES=60
ENABLE_ENCRYPTION=true
ENABLE_AUDIT_LOG=true

# Privacy
GDPR_MODE=true
ALLOW_DATA_EXPORT=true
ALLOW_DATA_DELETION=true
ANONYMIZE_OLD_DATA=false

# Monitoring
LOG_LEVEL=INFO
ENABLE_METRICS=true
ENABLE_PROFILING=false

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:8000
CORS_CREDENTIALS=true

# Rate Limiting
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=60
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Generated Keys:"
echo "   - SECRET_KEY: ${SECRET_KEY:0:20}..."
echo "   - ENCRYPTION_KEY: ${ENCRYPTION_KEY:0:20}..."
echo "   - JWT_SECRET_KEY: ${JWT_SECRET_KEY:0:20}..."
echo ""
echo "✅ Generated Passwords:"
echo "   - PostgreSQL: ${POSTGRES_PASSWORD:0:10}..."
echo "   - Redis: ${REDIS_PASSWORD:0:10}..."
echo "   - MinIO: ${MINIO_ROOT_PASSWORD:0:10}..."
echo ""

if [ "$GITHUB_CLIENT_ID" != "your-github-client-id" ]; then
    echo "✅ GitHub OAuth configured"
else
    echo "⚠️  GitHub OAuth not configured (you can add it later)"
fi

if [ "$GOOGLE_CLIENT_ID" != "your-google-client-id" ]; then
    echo "✅ Google OAuth configured"
else
    echo "⚠️  Google OAuth not configured (you can add it later)"
fi

if [ "$TWITTER_CLIENT_ID" != "your-twitter-client-id" ]; then
    echo "✅ Twitter OAuth configured"
else
    echo "⚠️  Twitter OAuth not configured (you can add it later)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Next Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Review the .env file:"
echo "   cat .env"
echo ""
echo "2. (Optional) Add OAuth credentials if you skipped them:"
echo "   - See docs/ENV_SETUP.md for detailed instructions"
echo "   - Edit .env manually"
echo ""
echo "3. Start the application:"
echo "   docker-compose up -d"
echo ""
echo "4. Check the logs:"
echo "   docker-compose logs -f"
echo ""
echo "5. Access the application:"
echo "   - Frontend: http://localhost:3000"
echo "   - Backend API: http://localhost:8000"
echo "   - API Docs: http://localhost:8000/api/docs"
echo ""
echo "6. Download Ollama models:"
echo "   docker exec -it lifemetrics-ollama ollama pull llama3.2"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IMPORTANT: Never commit the .env file to version control!"
echo "   It contains sensitive passwords and API keys."
echo ""
echo "📚 For more information, see:"
echo "   - docs/ENV_SETUP.md - Detailed environment setup guide"
echo "   - docs/SETUP.md - Complete setup guide"
echo "   - README.md - Project overview"
echo ""
